### ISSUE TITLE
V2.0

### ISSUE THREAD

**Issue by K-Phoen** [K-Phoen/SitemapGenerator#9]
Here is a roadmap of what I currently have in mind for a new version of this library. Most of the items listed here are taken from [this issue](https://github.com/K-Phoen/SitemapGenerator/issues/4).
- [x] Coding Standard/Style:
  - [x] Add CS checking
  - [x] Docblocks
    - [x] Remove "noise" (like: string $url The URL <- Makes no sense IMO) : #8
    - [x] Add dockblocks when missing
    - [x] Fix dockblocks where something is wrong (like Entitymanager instead of RouteInterface
  - [x] _Add editorconfig_
- [ ] Code
  - [x] Array typehints (`setImages`, `setVideos`)
  - [x] Drop `Interface` suffix: Symfony, Zend and the FIG still pushes it, but fortunately more and more developers realize, it's evil (reference: http://verraes.net/2013/09/sensible-interfaces/)
  - [ ] Separate `AbstractProvider` into smaller components: extract route generation logic
  - [x] _Remove `BaseFormatter`_
- [x] Package
  - [x] Add a CONTRIBUTING guide
  - [x] Remove unnecessary defaults from PHPUnit config
  - [x] Change to PSR-4 autoloading (and remove unnecessary custom ones)
  - [x] _Separate components requiring external dependencies into separate packages (doctrine, propel)_ : #5
  - [x] Unit test against lowest dependencies
- [ ] New Features
  - [ ] Add support for custom types: http://www.sitemaps.org/protocol.html#extending : #6
  - [ ] Add support for setting sitemap options directly in route options (RouteCollectionProvider)
  - [ ] Add a caching layer for providers with expensive calculations : #7
  - [x] Add a `ChangeFrequency` class/interface with common change constants
  - [x] _Move the package to an organization_

Items in _italic_ are items that are currently under consideration.
